/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BrioSideDrawer {
        "titulo": string;
    }
}
declare global {
    interface HTMLBrioSideDrawerElement extends Components.BrioSideDrawer, HTMLStencilElement {
    }
    var HTMLBrioSideDrawerElement: {
        prototype: HTMLBrioSideDrawerElement;
        new (): HTMLBrioSideDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "brio-side-drawer": HTMLBrioSideDrawerElement;
    }
}
declare namespace LocalJSX {
    interface BrioSideDrawer {
        "titulo"?: string;
    }
    interface IntrinsicElements {
        "brio-side-drawer": BrioSideDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "brio-side-drawer": LocalJSX.BrioSideDrawer & JSXBase.HTMLAttributes<HTMLBrioSideDrawerElement>;
        }
    }
}
